development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 10
  database: prodigit_developement
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 10
  database: prodigit_test
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 10
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['PRODUCTION_USERNAME'] %>
  password: <%= ENV['PRODUCTION_PASSWORD'] %>
  socket: /tmp/mysql.sock
